"""add created_at to profiles

Revision ID: ef8a9683eb51
Revises: 0984ed674fcb
Create Date: 2026-03-12 20:52:43.274935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8a9683eb51'
down_revision: Union[str, Sequence[str], None] = '0984ed674fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'created_at')
    # ### end Alembic commands ###
